### ISSUE TITLE
import xgboost error

### ISSUE THREAD

**Issue by sjl070707** [dask/dask-xgboost#1]
currently on dask 1.14 [complete] (from pip)
dask-xgboost also installed (from pip)
xgb 0.62 ubuntu 64

following error occurs.

import dask_xgboost

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-e033e148306e> in <module>()
----> 1 import dask_xgboost

/work/miniconda/lib/python3.5/site-packages/dask_xgboost/__init__.py in <module>()
----> 1 from .core import _train, train, predict

/work/miniconda/lib/python3.5/site-packages/dask_xgboost/core.py in <module>()
     12 from distributed.client import _wait
     13 from distributed.utils import sync
---> 14 from distributed.comm.core import parse_host_port
     15 import xgboost as xgb
     16 

ImportError: cannot import name 'parse_host_port'

===========================================================

according to the documentation,
parse_host_port exists in distributed.comm.addressing
rather than distributed.comm.core

http://distributed.readthedocs.io/en/latest/_modules/distributed/comm/addressing.html?highlight=parse_host_port

**Comment by sjl070707** [comment]
I forked your repo and modified 1 line to point it to the correct api.
tested and i was able to import dask xgb with success

https://github.com/sjl070707/dask-xgboost/commit/9d1b2c228763c8e7eb3c65b1c413366b7bb56d1a

**Comment by sjl070707** [comment]
I downgraded my xgboost to 0.60 and it loaded with pip installed dask_xgboost

**Comment by mrocklin** [comment]
Would you like to submit a PR with your fix?
