### ISSUE TITLE
train rabit module

### ISSUE THREAD

**Issue by galfaroi** [dask/dask-xgboost#17]
Hi,

I have the following issue after I run: 
bst = dxgb.train(client, params, X, y)

/usr/local/lib/python2.7/dist-packages/dask_xgboost/core.pyc in train_part()
     69 
     70     args = [('%s=%s' % item).encode() for item in env.items()]
---> 71     xgb.rabit.init(args)
     72     try:
     73         logger.info("Starting Rabit, Rank %d", xgb.rabit.get_rank())

AttributeError: 'module' object has no attribute 'rabit'

I already reinstalled xgboost 

Thanks for your help

**Comment by mrocklin** [comment]
```python
In [1]: import xgboost as xgb

In [2]: xgb.rabit
Out[2]: <module 'xgboost.rabit' from '/home/mrocklin/Software/anaconda/lib/python3.6/site-packages/xgboost/rabit.py'>

In [3]: xgb.__version__
Out[3]: '0.7.post3'
```

What version of xgboost do you have?

**Comment by galfaroi** [comment]
Hi  Matthew

I have 

In [1]: import xgboost

In [2]: print xgboost.__version__
0.4

**Comment by mrocklin** [comment]
I suspect that you have an old version of XGBoost that does not include the rabit module in the right place.  It would be useful to know what version this is so that we can update our minimum requirements.  Do you have any additional information here?

**Comment by galfaroi** [comment]
Updated seems to work, thanks!
