### ISSUE TITLE
only one worker used out of 2 available

### ISSUE THREAD

**Issue by alokgogate** [dask/dask-xgboost#22]
I have 3 machines (physical). One is the scheduler, and 2 separate machines for workers (one worker process on both machines respectively). When I submit a dask_xgboost job I can see that only one worker is being used and not all of them. Any clue as to why this may be happening? Also when I submit 2 jobs simultaneously, then also only one worker is being used.

dask - 0.16.1
dask-glm - 0.1.0
dask-ml - 0.6.0
dask-searchcv - 0.2.0
dask-xgboost - 0.1.5

**Comment by mrocklin** [comment]
Repeated question.   Closing.  Please don't repeat issues.

https://github.com/dask/distributed/issues/2097

**Comment by mrocklin** [comment]
Or close the other one and I'll open this one back up.  Up to you.
