### ISSUE TITLE
'return' with argument error on dask_xgboost import

### ISSUE THREAD

**Issue by andmib** [dask/dask-xgboost#3]
When trying to import dask_xgboost (installed via `pip`), I get the error:

```
File "/usr/local/lib/python2.7/dist-packages/dask_xgboost/core.py", line 126
    return result
SyntaxError: 'return' with argument inside generator
```

Thoughts?

**Comment by mrocklin** [comment]
Looks like we're not cleanly supporting Python 2.  This should be changed
to

    raise gen.Return(result)

I'll endeavor to clean this up sometime later today

**Comment by andmib** [comment]
That worked, I appreciate it.

**Comment by mrocklin** [comment]
Any interest in submitting a PR with the fix?

**Comment by andmib** [comment]
Honestly, I'm not entirely sure how to do that :/

**Comment by mrocklin** [comment]
I've pushed a fix

**Comment by andmib** [comment]
Thanks, sorry I couldn't be more help on that.
