### ISSUE TITLE
Migrate to XGBoost mainline repository

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-xgboost#39]
@RAMitchell (an xgboost maintainer) was mentioning that it might be possible to migrate the whole of the dask-xgboost codebase into xgboost itself.

Any thoughts or concerns about this?

I think that the proposed API change would be to add a `dask_client=` keyword (or something similar) to the official `train` and `predict` methods.

**Comment by TomAugspurger** [comment]
No objections here, though I think the CI is failing with the latest xgboost. I have a half-written tutorial copying https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html. I’ll try to finish that up in a couple weeks.

**Comment by javabrett** [comment]
Someone should verify that this code with [license (BSD 3-clause)](https://github.com/dask/dask-xgboost/blob/master/LICENSE.txt) can be absorbed into and under [their license (ASF 2.0)](https://github.com/dmlc/xgboost/blob/master/LICENSE) without changes.

I expect this is fine as BSD-3-clause is permissive, but best make sure they have checked before they accept the code, that no relicensing is required.

**Comment by jakirkham** [comment]
As xgboost now has native Dask support in mainline ( https://github.com/dmlc/xgboost/pull/4473 ), what would like to do with this repo?

**Comment by TomAugspurger** [comment]
At least update the readme, possible add a warning on import.

**Comment by TomAugspurger** [comment]
Will want to wait until there’s an XGBoost release though.

**Comment by jakirkham** [comment]
That sounds reasonable. How do we handle new issues that are reported here?

**Comment by mrocklin** [comment]
Just to be clear, the solution in XGBoost is quite a bit different than
what is implemented in this repository.  Folks may want to familiarize
themselves with their solution before deprecating this repository entirely.

**Comment by ksangeek** [comment]
@mrocklin Could you please elaborate a bit on how the implementation in this repository is different from the one included in dmlc/xgboost? And if you have some more time on what circumstances this one could be preferred?

**Comment by mrocklin** [comment]
I don't know the other implementation particularly well.  I recommend
reading their docs to get a more authoritative perspective.

https://xgboost.readthedocs.io/en/latest/python/python_api.html#module-xgboost.dask

**Comment by RAMitchell** [comment]
@ksangeek See demos here: https://github.com/dmlc/xgboost/tree/master/demo/dask

The xgboost dask integration is currently slightly more low-level than what is here. We are currently considering if we can extend the API to provide more high level functionality currently available in dask-xgboost without duplicating existing xgboost APIs. If this can be achieved we should be able to definitively move users from dask-xgboost to native xgboost integration and deprecate this without loss of user experience.

**Comment by ksangeek** [comment]
Thank you @mrocklin and @RAMitchell for the useful information.

**Comment by kylejn27** [comment]
Has this been thought about further? There's functionality in this library that I'd like to implement that's already been done in dmlc/xgboost's native dask integration

**Comment by TomAugspurger** [comment]
From what I understand, the implementation in xgboost is closer to what we have here now.

Personally, I'd like to see this handled within xgboost itself, to reduce the maintenance load here :)

Are there any features within dask-xgboost not handled within xgboost itself?

**Comment by kylejn27** [comment]
> the implementation in xgboost is closer to what we have here now.
I've been bouncing around the two codebases in the past few weeks, their implementation is extremely similar to what's in this repo, but supports more features in the underlying xgboost library

> Are there any features within dask-xgboost not handled within xgboost itself
Nope. The peers that I work with are requesting features for this library that have already been implemented in the native xgboost dask implementation

**Comment by TomAugspurger** [comment]
This topic came up in the monthly Dask meeting today. On the call @kylejn27 repeated that dmlc/xgboost handles everything dask-xgboost handles and more. If that is the case then maintaining dask-xgboost is wasted effort.

XGBoost hasn't made a release since the refactored dask handling went in. So we'll need to wait until their next release before making any concrete decisions. But my preference is to gather feedback from users (here and from followers of the dask_dev Twitter account) on whether the implementation in dmlc/xgboost suffices after the next release. If so, then we'll archive this repository and direct people there.

**Comment by hcho3** [comment]
FYI, I am currently working on the upcoming release for XGBoost (1.0.0). ETA is tomorrow (2/19).

**Comment by jakirkham** [comment]
@mmccarty @kylejn27 @gforsyth, would it be possible to get a summary of the current outstanding issues for migrating to xgboost for Dask usage?

cc @JohnZed (for vis)

**Comment by jakirkham** [comment]
On a different note, there is currently an RC for `xgboost` 1.2.0. Would be great if people can try and share feedback here ( https://github.com/dmlc/xgboost/issues/5970 ).

**Comment by trivialfis** [comment]
Please loop me in to related issues around migration.

**Comment by mmccarty** [comment]
This are the issues that I'm aware of
 - dmlc/xgboost#5765
 - dmlc/xgboost#5619
 - dmlc/xgboost#5495

**Comment by jameslamb** [comment]
Now that release 1.3.0 is out (congrats!!!) and it includes fixes for all the issues in https://github.com/dask/dask-xgboost/issues/39#issuecomment-681974273, can this be closed?

**Comment by jakirkham** [comment]
> Now that release 1.3.0 is out (congrats!!!) and it includes fixes for all the issues in [#39 (comment)](https://github.com/dask/dask-xgboost/issues/39#issuecomment-681974273), can this be closed?

@mmccarty? 🙂

**Comment by mmccarty** [comment]
Yes! Let's close this issue. Thank you everyone for the hard work!
