### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by ksangeek** [dask/dask-xgboost#45]
I see the latest released version of dask-xgboost is `0.1.5` and on `18 Nov 2017`. Multiple fixes have gone in after that! 
@mrocklin @TomAugspurger Could you please suggest if it is a good time to have a new release?

**Comment by TomAugspurger** [comment]
I can push a release today. It's a bit tricky since our CI has been broken on newer versions of XGBoost (just the testing; the actual package *should* be OK).

**Comment by ksangeek** [comment]
Okay. @TomAugspurger do you have information on which was the latest version of XGBoost where the test cases passed?

**Comment by TomAugspurger** [comment]
I'm not sure.

**Comment by TomAugspurger** [comment]
0.1.7 (I messed up 0.1.6) is out on PyPI, and Conda-forge packages are building now!
