### ISSUE TITLE
dashboard updates

### ISSUE THREAD

**Issue by quasiben** [dask/dask-xgboost#48]
When using dask-xgboost I see the profile dashboard page update but nothing in the task stream or progress panes.  Is this expected ?

**Comment by mrocklin** [comment]
Can you verify that other tasks submitted from your client show up?

Can you verify that you're using the operations found in this library and not the solution in the xgboost documentation (which is a separate implementation)

**Comment by quasiben** [comment]
Other tasks show up in the dashboard.  I *am* using the xgboost implementation from dmlc/rapids.    Should I file an issue with https://github.com/dmlc/xgboost/ ?

**Comment by mrocklin** [comment]
Does that code use tooling like `compute/persist/submit/map`, which generate tasks, or does it use `.run` which doesn't?

**Comment by mrocklin** [comment]
Regardless, at this point it's not a bug in the dask-xgboost implementation, but yes, it's an issue with dmlx/xgboost.

Whether or not it's a bug is up to them though.  They may have chosen to use run for a reason.

**Comment by quasiben** [comment]
Thanks for commenting!

They are using `run()`
