### ISSUE TITLE
Problem with rabit.init

### ISSUE THREAD

**Issue by mrphilroth** [dask/dask-xgboost#5]
After modifying the code with PR #4, I'm now running into errors when xgboost's rabit is started:

```
retry connect to ip(retry time 1): [localhost]
retry connect to ip(retry time 2): [localhost]
retry connect to ip(retry time 3): [localhost]
retry connect to ip(retry time 4): [localhost]
connect to (failed): [localhost]
Socket Connect Error:Invalid argument
distributed.nanny - WARNING - Worker process 34605 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
```

These are logs from a local worker on my laptop when `xgb.rabit.init(args)` is called. I'm not sure how to go about debugging this.

**Comment by mrocklin** [comment]
Perhaps rabit doesn't like the name `localhost`?  If you're starting with `LocalCluster` then maybe try starting with the command line `dask-scheduler` and `dask-worker` command line executables.

http://distributed.readthedocs.io/en/latest/setup.html

**Comment by mrphilroth** [comment]
Yeah. You're right. I don't think rabit likes `localhost`. I already was using `dask-scheduler` and `dask-worker` from the command line. A quick attempt at `LocalCluster` failed because of errors like this:

```
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

but that might be unrelated and solvable if I dig into it. Instead, I used `dask-ec2` to bring up a cluster and successfully trained a model from beginning to end. Closing the issue...

Thanks for your help!

**Comment by mrocklin** [comment]
If you want to use LocalCluster in a python script you need to put it
within the `if __name__ == '__main__':` block
