### ISSUE TITLE
normalize_estimator function trying to access non-existent attribute

### ISSUE THREAD

**Issue by blinickg** [dask/dask-xgboost#72]
See thread here: https://github.com/dask/dask-ml/issues/667

Proposing a change to subclass `AttributeError` to make it clear that you're accessing a non-existent attribute when calling the `normalize_estimator` function before training.

**Comment by TomAugspurger** [comment]
@blinickg I believe this should go in https://github.com/dmlc/xgboost, not here :) That's where the XGBoostError is raised.

**Comment by blinickg** [comment]
Ah, OK. Thanks @TomAugspurger
