### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by jameslamb** [dask/dask-xgboost#75]
Thanks for maintaining this awesome package! I'm really digging it.

Would you consider doing a minor release to PyPi? The last one (`1.10.0`) was [about 6 months ago](https://github.com/dask/dask-xgboost/releases/tag/0.1.10), and I'm relying on installing from GitHub right now to get this fix: #40 

Thanks for your time and consideration

**Comment by TomAugspurger** [comment]
I can do one today or next week. Anything you want to get in first
@gforsyth?

**Comment by gforsyth** [comment]
Thanks for the ping @TomAugspurger -- I think @mmccarty covered the major footguns in his PR.  One thing we need to do following the pypi release is to update the conda-forge feedstock and pin `xgboost` to `0.90` (or `<=0.90`)

**Comment by jakirkham** [comment]
Should [this line]( https://github.com/dask/dask-xgboost/blob/34f9b66cbc5eff9adb545e19009a2dff7120ebd0/requirements.txt#L1 ) also be `<=0.90`?

**Comment by mmccarty** [comment]
If we want to pin `xgboost` to `<=0.90`, yes.

**Comment by gforsyth** [comment]
I was in the middle of answering this on Friday and then got distracted (sorry).

I think `<=0.90` is probably the way to go.  There is probably some low version that will break, but we can cross that bridge if and when we come to it, and there's no reason to exclude 0.80 for the moment.

**Comment by TomAugspurger** [comment]
Uploaded to [PyPI](https://pypi.org/project/dask-xgboost/0.1.11/). conda-forge bots should pick it up later today.

**Comment by jameslamb** [comment]
Thanks!
