### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by jsignell** [dask/dask-xgboost#80]
Since the functionality has been moved to xgboost itself. Would now be the appropriate time to archive this repo?

**Comment by jrbourbeau** [comment]
cc @TomAugspurger @mmccarty @gforsyth

**Comment by gforsyth** [comment]
We've moved our work over to `xgboost.dask`, so for our purposes, anyway, this repo can be archived.

**Comment by jakirkham** [comment]
SGTM. Should we update the README to reflect this?

**Comment by jrbourbeau** [comment]
That sounds good. Similar to `dask-lightgbm`, we might also consider issuing a final release before archiving which adds a warning that the functionality in `dask-xgboost` has been moved into `xgboost` and `dask-xgboost` is no longer maintained

**Comment by trivialfis** [comment]
Can we wait for xgb 1.4?  I would like to get the integrated version feature complete at this version.

**Comment by TomAugspurger** [comment]
Adding a warning, updating the docs, and archiving sounds good to me.

**Comment by JohnZed** [comment]
In the near future, I'd be totally onboard with archiving. But I agree with @trivialfis - there are still a few more minor bits coming for xgboost.dask in 1.4 (DART algo comes to mind?), so archiving this project after 1.4 is out would sound most appealing, as then we can clearly say there is no reason to use it for any new code.

**Comment by trivialfis** [comment]
Hi, XGBoost 1.4.1 is out and available on pypi.  I believe we can safely redirect users to the `xgboost.dask` module in the future as it's mostly feature-complete now.  Thanks for the excellent work everyone!  ;-)

**Comment by jsignell** [comment]
Great! So what's needed is a note on the readme and then for someone to push the "archive button"?

**Comment by jrbourbeau** [comment]
Adding a promonant note to the README sounds good. I'll propose we also add a warning which points users to `xgboost.dask` (similar to what we did [with `dask-lightgbm`](https://github.com/dask/dask-lightgbm/pull/30)) and issue a final release.

**Comment by jakirkham** [comment]
There's also some references to Dask-XGBoost in Dask-ML ( https://github.com/dask/dask-ml/issues/844 ). We may want to remove those as well.

**Comment by jrbourbeau** [comment]
Just pushed out 0.2.0 which contains deprecation warnings (xref https://github.com/dask/dask-xgboost/pull/84). Planning to archive this repo tomorrow morning (in the central time zone)

**Comment by jakirkham** [comment]
Thanks James! 😄
