### ISSUE TITLE
Support new version of xgboost? 

### ISSUE THREAD

**Issue by cookielee77** [dask/dask-xgboost#83]
Thanks for amazing package! Current version only supports xgboost <=0.90, but we used a newer version of xgboost >= 1.00. I'm wondering whether there is a plan to support the newer version of xgboost in the near future? 

Thanks!

**Comment by mrocklin** [comment]
Hi @cookielee77 !  You may also be interested in using the xgboost.dask package.  See https://xgboost.readthedocs.io/en/latest/tutorials/dask.html

**Comment by cookielee77** [comment]
Thanks for the quick response! I'm wondering whether the difference between the xgboost.dask package in the above page and xgboost in dask_ml (which requires dask-xgboost)?

**Comment by jrbourbeau** [comment]
@cookielee77, good question. The functionality in `dask-xgboost` has been upstreamed and included in the main `xgboost` package (that's the `xgboost.dask` package @mrocklin was referencing). We will soon deprecate `dask-xgboost` and recommend users move to `xgboost.dask` instead (xref https://github.com/dask/dask-xgboost/issues/80).

**Comment by cookielee77** [comment]
Thanks for the clarification!

**Comment by jakirkham** [comment]
Yes please use xgboost for this functionality.
