### ISSUE TITLE
Incorrect overly simple model is returned

### ISSUE THREAD

**Issue by mrphilroth** [dask/dask-xgboost#9]
No matter how much I play with the input data or xgboost parameters, I can only get dask_xgboost.train to return an overly simple model that has 10 trees with a single leaf node on each tree. While training locally, I have output that looks like:

```
[18:55:12] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[18:55:12] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[18:55:12] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[18:55:12] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[18:55:12] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[18:55:12] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[18:55:12] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
[18:55:12] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 0 extra nodes, 0 pruned nodes, max_depth=0
```
I'm guessing that this means the training parameters aren't making it to the xgboost train method, but printing those out immediately before the `xgb.train(param, dtrain, **kwargs)` call shows that each instance of this function has the correct parameters that are specifying a nonzero max_depth and many more n_estimators than 10.

You can test to see if your training outputs look like this with:

```
In [96]: bst = xgboost.Booster(model_file="saved_model.xgb")

In [97]: bst.get_dump()
Out[97]:
['0:leaf=-0.749752\n',
 '0:leaf=-0.551972\n',
 '0:leaf=-0.476789\n',
 '0:leaf=-0.43804\n',
 '0:leaf=-0.415481\n',
 '0:leaf=-0.401443\n',
 '0:leaf=-0.392314\n',
 '0:leaf=-0.386148\n',
 '0:leaf=-0.381795\n',
 '0:leaf=-0.378518\n']
```
My leaf values vary, but the structure of the model doesn't change.

**Comment by mrocklin** [comment]
Interesting.  While building this I have to admit that I was more concerned with getting the distributed systems to play nicely together and less interested in checking correctness.  Looking through things again it certainly looks like we're passing all of the parameters through, but my experience as an XGBoost user is quite limited and it's possible that I'm missing something.  

@mrphilroth do you have a moment to look through the codebase to see if anythin  catches your eye as problematic?  It's quite small, https://github.com/dask/dask-xgboost/blob/master/dask_xgboost/core.py

**Comment by mrphilroth** [comment]
I'm guilty of the same thing! I've been happily training models just trying to get my data pipeline correct without checking the actual models till now.

I've been debugging the code and trying lots of things out. I'll keep doing that. This is more of a "Hey, I might need more help than I thought" issue filing. So far, the code in this repo looks like it's doing what it should be doing. I may have to move on to understanding the rabit and xgboost python packages to see if that's where the problem lies.

**Comment by mrocklin** [comment]
My first instinct here is to try to isolate the problem to either dask-xgboost or xgboost proper. If the problem is in the latter project then I would raise upstream.  They'll be much better equipped to handle it if so.

**Comment by mrocklin** [comment]
Thank you for raising this issue regardless.

**Comment by TomAugspurger** [comment]
@mrphilroth what's in your `kwargs`, specifically, do you set `num_boost_round`? This confused me last week, since the xgboost docs use a bunch of different names for that argument.

**Comment by TomAugspurger** [comment]
```python
In [33]: from sklearn.datasets import make_classification

In [34]: X, y = make_classification()

In [35]: X = da.from_array(X, chunks=50)

In [36]: y = da.from_array(y, chunks=50)

In [37]: import dask.array as da

In [38]: bst1 = dxgb.train(client, params, X, y); bst2 = dxgb.train(client, params, X, y, num_boost_round=100)

In [39]: bst1.best_ntree_limit
Out[39]: 10

In [40]: bst2.best_ntree_limit
Out[40]: 100
```

**Comment by mrphilroth** [comment]
@TomAugspurger That example was compelling enough for me to go back and get rid of all my parameters except num_boost_round. Then it worked! I probably had one parameter that worked on my single machine but can't work when going distributed. I'm guessing this caused xgboost to use dummy parameters instead of my invalid ones.

If I figure out which one was wrong I'll reply here for future Google'ers. Otherwise, this is solved and it was my problem and not dask-xgboost's. Sorry for the noise and thanks for the help.
